
str.NMD = '/home/jason/lammps/LJ/alloy/10K/0.0/10x/NMD/1';

SEDper=load(strcat(str.NMD,'/SEDdata.mat'));

str.NMD = '/home/jason/lammps/LJ/alloy/10K/0.05/10x/NMD/1';

NMD=load(strcat(str.NMD,'/NMDdata.mat'));

SED=load(strcat(str.NMD,'/SEDdata.mat'));

ALLOY.sedfreq=1;

%re-sort eigvec and transpose freq
for ikpt = 1:NMD.NUM_KPTS
        eig(...
            (ikpt-1)*NMD.NUM_MODES+1:(ikpt)*NMD.NUM_MODES,...
            1:3*NMD.NUM_ATOMS_UCELL)...
            =...
        NMD.eigvec( (NMD.NUM_ATOMS_UCELL*3)*(ikpt-1)+1 ...
            :...
            ((NMD.NUM_ATOMS_UCELL*3)*ikpt),   1:NMD.NUM_MODES      )';  
        
        ALLOY.freq(...
            (ikpt-1)*NMD.NUM_MODES+1:(ikpt)*NMD.NUM_MODES,1)...
            =...
            NMD.freq(ikpt,:)';
        
        ALLOY.sedfreq(...
            (ikpt-1)*NMD.NUM_MODES+1:(ikpt)*NMD.NUM_MODES,1)...
            =...
            SED.redkpt.freq(ikpt,:)';
        
        ALLOY.life_pp(...
            (ikpt-1)*NMD.NUM_MODES+1:(ikpt)*NMD.NUM_MODES,1)...
            =...
            SEDper.redkpt.life(1:NMD.NUM_MODES , ikpt);
        
        ALLOY.life_d(...
            (ikpt-1)*NMD.NUM_MODES+1:(ikpt)*NMD.NUM_MODES,1)...
            =...
            SED.redkpt.life(1:NMD.NUM_MODES , ikpt);
            
%         NMD.eigvec( (NMD.NUM_ATOMS_UCELL*3)*(ikpt-1)+1 ...
%             :...
%             ((NMD.NUM_ATOMS_UCELL*3)*ikpt),   1:NMD.NUM_MODES      )'
end

%DOS 
%[y x ]=hist(freq,17); loglog(x,y,'.',x,5*(x.^2))

%--------------------------------------------------------------------------
%pause
%--------------------------------------------------------------------------


for imode = 1:size(eig,1)
imode
    g(1) =...
        (1-NMD.alloy_conc)* ((1 - (NMD.m(1)/NMD.vm) )^2) ... 
        +...
        (NMD.alloy_conc)* ((1 - (NMD.m(2)/NMD.vm) )^2);
%find all e*(k',v') dot e(k,v), sum over b
    SUMb =...
        g(1)*...
        abs(...
        sum(...
        bsxfun(...
        @times, eig(:,:)  ,  conj(eig(imode,:)) ),2) ...
        ).^2 ;
%set self-term 0
    SUMb(imode) = 0;
%
ALLOY.dw_avg =...
    real(...
    mean(...
    ALLOY.freq(2:NMD.NUM_MODES)...
    -...
    ALLOY.freq(1:NMD.NUM_MODES-1)));
delwij = ...
    ALLOY.freq - ALLOY.freq(imode);
lor = (1.0/pi)*(ALLOY.dw_avg./( delwij.^2 + ALLOY.dw_avg^2 ) );

    ALLOY.life(imode) =...
        ( pi*(ALLOY.freq(imode)^2) ) / ( 2*NMD.Nx*NMD.Ny*NMD.Nz )*...
        sum(lor.*SUMb,1);
    
    ALLOY.life(imode) = 1/ALLOY.life(imode);
        
%         eigx =...
%             eigenvec(...
%             ((NMD.NUM_ATOMS_UCELL*3)*(kindex-1)+1)... 
%             :3:...
%             ((NMD.NUM_ATOMS_UCELL*3)*kindex),   imode      );
end

[I,J] = sort(ALLOY.freq);

loglog(ALLOY.freq(J),ALLOY.life(J)*NMD.LJ.tau,...
    ALLOY.freq(J), 1*ALLOY.freq(J).^(-4),...
SEDper.irrkpt.sedfreq,SEDper.irrkpt.life,'.',...
SED.irrkpt.sedfreq,SED.irrkpt.life,'.')

save(strcat(str.NMD,'/ALLOY.mat'), '-struct', 'ALLOY');

%re-sort eigvec and transpose freq
% for ikpt = 1:NMD.NUM_KPTS
%     
%         ALLOY.life(...
%             (ikpt-1)*NMD.NUM_MODES+1:(ikpt)*NMD.NUM_MODES,1)...
%             =...
%         ALLOY
%     
%         ALLOY.freq(...
%             (ikpt-1)*NMD.NUM_MODES+1:(ikpt)*NMD.NUM_MODES,1)...
%             =...
%             NMD.freq(ikpt,:)';
%         ALLOY.life(
%             
% %         NMD.eigvec( (NMD.NUM_ATOMS_UCELL*3)*(ikpt-1)+1 ...
% %             :...
% %             ((NMD.NUM_ATOMS_UCELL*3)*ikpt),   1:NMD.NUM_MODES      )'
% end


