function gulp = m_coords2gulp( gulp, x0 )
	 formats ='%2.6f'
	 %{
	
	  %}
      if strcmp(x0.type(2).str,'GAMMA')
	 for l=1:1:length(x0.pos(:,1))
		if x0.pos(l,2) == 1
			gulp.coords1{l}=strcat(x0.atype(1).str,'   core     \t',...
					num2str(x0.LJ.sigma.*(1e10).*x0.pos(l,3),formats),'\t',...
					num2str(x0.LJ.sigma.*(1e10).*x0.pos(l,4),formats),'\t',...
					num2str(x0.LJ.sigma.*(1e10).*x0.pos(l,5),formats),'\t',...
					'     0 1 1 1')
		else		  
			gulp.coords1{l}=strcat(x0.atype(2).str,'   core    \t',...
					num2str(x0.LJ.sigma.*(1e10).*x0.pos(l,3),formats),'\t',...
					num2str(x0.LJ.sigma.*(1e10).*x0.pos(l,4),formats),'\t',...
					num2str(x0.LJ.sigma.*(1e10).*x0.pos(l,5),formats),'\t',...
					'     0 1 1 1')
		end
	 end
       else
	 for l=1:1:length(x0.superlattice.direct(:,1))
		if x0.m(l) == 1
			gulp.coords1{l}=strcat(x0.atype(1).str,'   core     \t',...
					num2str(x0.LJ.sigma.*(1e10).*x0.ucell.cart(l,1),formats),'\t',...
					num2str(x0.LJ.sigma.*(1e10).*x0.ucell.cart(l,2),formats),'\t',...
					num2str(x0.LJ.sigma.*(1e10).*x0.ucell.cart(l,3),formats),'\t',...
					'     0 1 1 1')
		else		  
			gulp.coords1{l}=strcat(x0.atype(2).str,'   core    \t',...
					num2str(x0.LJ.sigma.*(1e10).*x0.ucell.cart(l,1),formats),'\t',...
					num2str(x0.LJ.sigma.*(1e10).*x0.ucell.cart(l,2),formats),'\t',...
					num2str(x0.LJ.sigma.*(1e10).*x0.ucell.cart(l,3),formats),'\t',...
					'     0 1 1 1')
		end
	 end
       end
	 gulp.coords = sprintf('%s \n',gulp.coords1{:})
end
